name: Build and Test DRM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build UltimateDRM.sln (Release x64)
      run: msbuild UltimateDRM.sln /p:Configuration=Release /p:Platform=x64

    - name: Run DRMTest.exe and capture output
      run: |
       ./x64/Release/DRMTest.exe > output.log 2>&1
        exit_code=$?
        echo "Exit code: $exit_code"
        type output.log
        exit $exit_code
        
    - name: Upload DRMTest output
      uses: actions/upload-artifact@v4
      with:
        name: DRMTestLog
        path: output.log
